---
# name (required)
# may be your real name or your nick
name: John Doe

# geo location (required)
# provide your favored level of detail by number of digits (like 50.107811 vs 50.11)
# you may use services like openstreetmap.org to find out your geo location
latitude: 50.11
longitude: 8.67

# bio
# describe yourself, your involvement in the project and the community or whatever is relevant for you.
# should be limited to the size of a tweet (140 chars).
bio: "Hey, I’m John, englishman living in Frankfurt am Main working for YAKAMOTO. I was involved into several REDAXO addons like structure 4.0, the wordpress importer and twitteredaxo. Find me at slack and in the forum."

# image or gravatar
# provide image file from current folder (like 'johndoe.jpg') or gravatar url (like 'https://www.gravatar.com/avatar/{HASH}')
# should be square and about 300 x 300 px size
image: johndoe.jpg

# links
# one or more links to your website, your github profile, twitter, facebook et al.
links:
- https://johndoe.me
- https://github.com/johndoe
- https://twitter.com/johndoe

---
